clone:
  git:
    image: quay.io/packet/drone-git

matrix:
  PYTHON_VERSION:
    # yes py35 is eol, but tinkerbell/osie still uses old ubuntu and py3.5... sigh
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9

pipeline:
  fmt_and_lint:
    image: python:3.8-alpine
    commands:
      - pip install black==19.3b0 pylama
      - black --check --diff .
      - pylama --ignore=E203 packetnetworking setup.py

  test:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install tox
      - tox -e py$(echo ${PYTHON_VERSION} | sed 's|\.||')
